FROM git.d464.sh/infra/os/kube:latest AS builder

# https://github.com/ItalyPaleAle/fcos-layers/blob/main/zfs/Containerfile

RUN rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}' | tee /kernel-version.txt

RUN rpm-ostree install --assumeyes --apply-live binutils gcc make autoconf automake libtool rpm-build libtirpc-devel libblkid-devel libuuid-devel libudev-devel openssl-devel zlib-devel libaio-devel libattr-devel elfutils-libelf-devel kernel-devel python3 python3-devel python3-setuptools python3-cffi libffi-devel git ncompress libcurl-devel python3-packaging dkms kernel kernel-modules kernel-devel #kernel-$(cat /kernel-version.txt) kernel-modules-$(cat /kernel-version.txt) kernel-devel-$(cat /kernel-version.txt)

WORKDIR /var/zfs
RUN mkdir bin && ln -s /usr/bin/ld.gold bin/ld
ENV PATH="/var/zfs/bin:${PATH}"

RUN git clone https://github.com/openzfs/zfs
WORKDIR /var/zfs/zfs
RUN git checkout master && \
	sh autogen.sh && \
	./configure --with-linux=/usr/src/kernels/$(cat /kernel-version.txt)/ --with-linux-obj=/usr/src/kernels/$(cat /kernel-version.txt)/
RUN make -s -j $(nproc) && \
	make rpm
RUN rm *.src.rpm && rm *debug*.rpm && rm zfs-test*.rpm

FROM git.d464.sh/infra/os/kube:latest

COPY --from=builder /var/zfs/zfs/*.rpm ./
RUN rpm-ostree install --assumeyes gcc samba *.rpm man smartmontools && rm *.rpm \
	&& depmod -a "$(rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')" \
    && echo "zfs" > /etc/modules-load.d/zfs.conf \
    && rm -rf /var/lib/pcp

RUN ln -s /usr/bin/man.man-db /usr/bin/man
RUN rpm-ostree override remove nfs-utils-coreos --install nfs-utils
RUN systemctl enable nfs-server smb zfs-scrub-monthly@borealis.timer zfs-scrub-monthly@blackmesa.timer

COPY include/gitea.container /usr/share/containers/systemd/gitea.container

# RUN ostree container commit
