FROM git.d464.sh/infra/os/base:latest

RUN rpm-ostree install neovim htop tcpdump systemd-networkd tmux wpa_supplicant python
RUN curl https://github.com/coredns/coredns/releases/download/v1.11.1/coredns_1.11.1_linux_amd64.tgz -L -o coredns.tgz && \
	tar -xf coredns.tgz && rm coredns.tgz && chmod 0755 coredns && mv coredns /usr/bin/

RUN mkdir -p /etc/router /etc/router/hosts.d/ /etc/router/forward.d/

COPY include/coredns.service /etc/systemd/system/
COPY include/router.service /etc/systemd/system/
COPY router /usr/bin/router

RUN systemctl disable NetworkManager
RUN systemctl enable systemd-networkd coredns router

RUN ostree container commit
