name: build
on: 
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * 1" # every monday, I think...
jobs:
  build:
    runs-on: [fedora-39]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_SERVER_URL }}
          username: ${{ env.GITHUB_ACTOR }}
          password: ${{ secrets.AUTH_TOKEN }}

      - name: build and push
        run: "PUSH=1 ./build.sh"
