name: build
on: 
  push:
    branches: [main]
  schedule:
    - "0 0 * * 1" # every monday, I think...
jobs:
  build:
    runs-on: [coreos-stable]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_SERVER_URL }}
          username: ${{ env.GITHUB_ACTOR }}
          password: ${{ secrets.AUTH_TOKEN }}

      - name: Build image
        run: docker build -t git.d464.sh/infra/nas:latest -f Containerfile .

      - name: Push image
        run: docker push git.d464.sh/infra/nas:latest
